name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  load:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Setup R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            devtools
      - name: Load
        run: R -e 'devtools::load_all()'